# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_instruction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='db_id_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recipe.RecipeIngredient'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.Recipe'),
        ),
    ]
