# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20171229_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='recipe.Ingredient'),
        ),
    ]
